BP_Administration_System/Controllers/EmployeeSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BP_Administration_System.Models;
using BP_Administration_System.Models.TableStorage;
using BP_Administration_System.Repositories;
using BP_Administration_System.Repositories.TableStorage;
using BP_Administration_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BP_Administration_System.Controllers
{
    public class EmployeeSettingsController : Controller
    {
        private readonly ITableStorageRepository<ApplicationSettings> _appSettingsRepository;
        private readonly ITableStorageRepository<ProfileSettings> _profileSettingsRepository;
        private readonly ILogger _logger;

        public EmployeeSettingsController
            (
            ITableStorageRepository<ApplicationSettings> appSettingsRepository,
            ITableStorageRepository<ProfileSettings> profileSettingsRepository,
            ILogger<EmployeeSettingsController> logger
            )
        {
            _appSettingsRepository = appSettingsRepository;
            _profileSettingsRepository = profileSettingsRepository;
            _logger = logger;
        }

        //Index EmployeeSettings
        public async Task<IActionResult> AllEmployeeSettings()
        {
            return View(new SettingsViewModel
            {
                applicationSettings = await _appSettingsRepository.GetEntitiesAsync(),
                profileSettings = await _profileSettingsRepository.GetEntitiesAsync()
            });
        }

        //Edit AppSettings GET
        public async Task<IActionResult> EditAppSettings(string partitionKey, string rowKey)
        {
            _logger.LogInformation("Editing Application Settings in {0}", nameof(EditAppSettings));

            if (partitionKey == null)
            {
                _logger.LogWarning("Partition Key {0} in {1} NOT FOUND", partitionKey, nameof(EditAppSettings));
                return NotFound();
            }
            ApplicationSettings appSettings = await _appSettingsRepository.GetEntityAsync(partitionKey, rowKey);

            if (appSettings == null)
            {
                _logger.LogWarning("Application Settings{0} in {1} NOT FOUND", appSettings, nameof(EditAppSettings));
                return NotFound();
            }

            return View(appSettings);
        }

        //Edit AppSettings POST
        [HttpPost]
        public async Task<IActionResult> EditAppSettings(ApplicationSettings appSettings)
        {
            if (ModelState.IsValid)
            {
                await _appSettingsRepository.UpdateEntityAsync(appSettings);

                TempData["noticeUpdated"] = "Application Settings were successfuly updated";
                return RedirectToAction("AllEmployeeSettings");
            }
            _logger.LogWarning("Application Settings {0} in {1} IS NOT VALID", appSettings, nameof(EditAppSettings));
            return View();
        }

        //Edit ProfileSettings GET
        public async Task<IActionResult> EditProfileSettings(string partitionKey, string rowKey)
        {
            _logger.LogInformation("Editing Profile Settings in {0}", nameof(EditProfileSettings));
            if (partitionKey == null)
            {
                _logger.LogWarning("Partition Key {0} in {1} NOT FOUND", partitionKey, nameof(EditProfileSettings));
                return NotFound();
            }
            ProfileSettings profileSettings = await _profileSettingsRepository.GetEntityAsync(partitionKey, rowKey);

            if (profileSettings == null)
            {
                _logger.LogWarning("Profile Settings{0} in {1} NOT FOUND", profileSettings, nameof(EditProfileSettings));
                return NotFound();
            }

            return View(profileSettings);
        }

        //Edit ProfileSettings POST
        [HttpPost]
        public async Task<IActionResult> EditProfileSettings(ProfileSettings profileSettings)
        {
            if (ModelState.IsValid)
            {
                await _profileSettingsRepository.UpdateEntityAsync(profileSettings);

                TempData["noticeUpdated"] = "Profile Settings were successfuly updated";
                return RedirectToAction("AllEmployeeSettings");
            }
            _logger.LogWarning("Profile Settings {0} in {1} IS NOT VALID", profileSettings, nameof(EditProfileSettings));
            return View();
        }
    }
}

BP_Administration_System/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BP_Administration_System.Models;
using BP_Administration_System.Repositories;
using BP_Administration_System.Repositories.BlobStorage;
using BP_Administration_System.Repositories.QueueStorage;
using BP_Administration_System.ViewModels;
using BP_Administration_System_Develop.Repositories.BlobStorage;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.WindowsAzure.Storage.Blob;


namespace BP_Administration_System.Controllers
{
    public class MediaController : Controller
    {
        private readonly IPhotosRepository _photosRepository;
        private readonly IVideosRepository _videosRepository;
        private readonly IQueueStorageRepository _queueRepository;
        private readonly ILogger _logger;

        public MediaController
            (
            IPhotosRepository photosRepository,
            IVideosRepository videosRepository,
            IQueueStorageRepository queueRepository,
            ILogger<MediaController> logger
            )
        {
            _photosRepository = photosRepository;
            _videosRepository = videosRepository;
            _queueRepository = queueRepository;
            _logger = logger;
        }

        //Index Media Storage GET
        public async Task<IActionResult> MediaIndex()
        {
            return View(new BlobsViewModel
            {
                photoBlobs = await _photosRepository.GetAllBlobsAsync(),
                videoBlobs = await _videosRepository.GetAllBlobsAsync()
            });
        }

        //Detail blobu GET
        public IActionResult ImageDetail(string blobName)
        {
            _logger.LogInformation("Getting item {0} in {1}", blobName, nameof(ImageDetail));
            if (blobName == null)
            {
                _logger.LogWarning("Detail of image {0} in {1} NOT FOUND", blobName, nameof(ImageDetail));
                return NotFound();
            }
            return View(new BlobsViewModel
            {
                blob = _photosRepository.GetBlob(blobName)
            });
        }

        //Upload image GET
        [ActionName("Upload")]
        public IActionResult UploadImageAsync()
        {
            return View();
        }

        //Upload image POST
        [HttpPost]
        [ActionName("Upload")]
        public async Task<IActionResult> UploadImageAsync(IFormFile imageFile)
        {
            _logger.LogInformation("Uploading image {0} in {1}", imageFile.FileName, nameof(UploadImageAsync));

            if (imageFile == null)
            {
                _logger.LogWarning("Cannot upload image {0} in {1} - BAD REQUEST", imageFile.FileName, nameof(UploadImageAsync));
                return BadRequest();
            }
            var blobObject = await _photosRepository.UploadBlobAsync(imageFile);
            await _queueRepository.AddMessageAsync(blobObject.Name);
            TempData["noticeCreated"] = "Image was successfuly uploaded";
            return RedirectToAction("MediaIndex");
        }

        //Download image 
        [ActionName("Download")]
        public async Task<IActionResult> DownloadImageAsync(string blobName)
        {
            _logger.LogInformation("Downloading image {0} in {1}", blobName, nameof(DownloadImageAsync));

            if (blobName == null)
            {
                _logger.LogWarning("Cannot download image {0} in {1} - NOT FOUND", blobName, nameof(DownloadImageAsync));
                return NotFound();
            }
            var stream = await _photosRepository.DownloadBlobAsync(blobName);
            return File(stream.ToArray(), "application/octet-stream", blobName);
        }

        //Delete image POST
        [HttpPost]
        public async Task<IActionResult> DeleteBlobAsync(string blobName)
        {
            _logger.LogInformation("Deleting image {0} in {1}", blobName, nameof(DeleteBlobAsync));

            if (blobName == null)
            {
                _logger.LogWarning("Cannot delete image {0} in {1} - NOT FOUND", blobName, nameof(DeleteBlobAsync));
                return NotFound();
            }
            await _photosRepository.DeleteBlobAsync(blobName);

            TempData["noticeDeleted"] = "Image was successfuly deleted";
            return RedirectToAction("MediaIndex");
        }

        //Upload video GET
        [ActionName("UploadVideo")]
        public IActionResult UploadVideoAsync()
        {
            return View();
        }

        //Upload video POST
        [HttpPost]
        [ActionName("UploadVideo")]
        public async Task<IActionResult> UploadVideoAsync(IFormFile videoFile)
        {
            _logger.LogInformation("Uploading video {0} in {1}", videoFile.FileName, nameof(UploadVideoAsync));

            if (videoFile == null)
            {
                _logger.LogWarning("Cannot upload video {0} in {1} - BAD REQUEST", videoFile.FileName, nameof(UploadVideoAsync));
                return BadRequest();
            }
            var blobObject = await _videosRepository.UploadBlobAsync(videoFile);
            TempData["noticeCreated"] = "Video was successfuly uploaded";
            return RedirectToAction("MediaIndex");
        }

        //Download video 
        [ActionName("DownloadVideo")]
        public async Task<IActionResult> DownloadVideoAsync(string blobName)
        {
            _logger.LogInformation("Downloading video {0} in {1}", blobName, nameof(DownloadVideoAsync));

            if (blobName == null)
            {
                _logger.LogWarning("Cannot download video {0} in {1} - NOT FOUND", blobName, nameof(DownloadVideoAsync));
                return NotFound();
            }
            var stream = await _videosRepository.DownloadBlobAsync(blobName);
            return File(stream.ToArray(), "application/octet-stream", blobName);
        }

        //Delete video POST
        [HttpPost]
        public async Task<IActionResult> DeleteVideoBlobAsync(string blobName)
        {
            _logger.LogInformation("Deleting video {0} in {1}", blobName, nameof(DeleteVideoBlobAsync));

            if (blobName == null)
            {
                _logger.LogWarning("Cannot delete video {0} in {1} - NOT FOUND", blobName, nameof(DeleteVideoBlobAsync));
                return NotFound();
            }
            await _videosRepository.DeleteBlobAsync(blobName);

            TempData["noticeDeleted"] = "Video was successfuly deleted";
            return RedirectToAction("MediaIndex");
        }
    }
}

BP_Administration_System/Views/Shared/_EmployeesSortedPartial.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Index";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.Label("First Name")
            </th>
            <th>
                @Html.Label("Last Name")
            </th>
            <th>
                @Html.Label("Salary")
            </th>
            <th>
                @Html.Label("Age")
            </th>
            <th>
                @Html.Label("Employee Detail")
            </th>
            <th>
                @Html.Label("Actions")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var employee in Model)
        {
            <tr>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => employee.FirstName)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => employee.LastName)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => employee.Salary)
                </td>
                <td class="col-md-2">
                    @Html.DisplayFor(modelItem => employee.Age)
                </td>
                <td class="col-md-2">
                    @Html.ActionLink("Show Detail", "EmployeeDetails", "Home", null, null, null, new { id = employee.EmployeeId }, new { @class = "btn btn btn-default" })
                </td>
                @using (Html.BeginForm("DeleteAsync", "Home", new { id = employee.EmployeeId }))
                {
                    <td class="col-md-2">
                        @Html.ActionLink("Edit", "Edit", "Home", null, null, null, new { id = employee.EmployeeId }, new { @class = "btn btn btn-info" })
                        <input type="submit" value="Delete" class="btn btn-danger" onclick="return confirm('Do you really want to delete Employee @employee.FullName ?');" />
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

BP_Administration_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Administration System</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Administration System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Create">Create Employee</a></li>
                    <li><a asp-area="" asp-controller="EmployeeSettings" asp-action="AllEmployeeSettings">Employee Settings</a></li>
                    <li><a asp-area="" asp-controller="Media" asp-action="MediaIndex">Employee Media Storage</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Martin Kočí</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BP_Administration_System/Views/Shared/_MeetingCenterDetailPartial.cshtml
@model MeetingCenter

<div class="container">
    <div class="row">
        <div class="col-md-6"><h3>Detail of Meeting Center - @Model.Name</h3></div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.Name) </strong></div>
        <div class="col-md-2">@Model.Name</div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.Address)</strong></div>
        <div class="col-md-2">@Model.Address</div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.MeetingRoomsCommaSeperated)</strong></div>
        <div class="col-md-2">@Model.MeetingRoomsCommaSeperated</div>
    </div>
</div>

BP_Administration_System/Views/Shared/_MeetingRoomDetailPartial.cshtml
@model MeetingRoom

<div class="container">
    <div class="row">
        <div class="col-md-6"><h3>Detail of Meeting Room - @Model.Name</h3></div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.Name)</strong></div>
        <div class="col-md-2">@Model.Name</div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.Capacity)</strong></div>
        <div class="col-md-2">
            @ViewBag.ActualRoomCapacity / @Model.Capacity
            @if (@ViewBag.ActualRoomCapacity == @Model.Capacity)
            {
                @Html.Label(null, "ROOM IS FULL", new { @class = "messageDeleted" })
            }
        </div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.Description)</strong></div>
        <div class="col-md-2">@Model.Description</div>
    </div>
    <div class="row">
        <div class="col-md-2"><strong>@Html.DisplayNameFor(model => Model.MeetingCenter)</strong></div>
        <div class="col-md-2">@Model.MeetingCenter.Name</div>
    </div>
</div>